import type { InternInfo } from "@/models/intern-info";
import { firebaseRegister, mockRegister } from "@saintrelion/data-access-layer";

// #region Firebase
firebaseRegister("InternInfo");

// #region Mock
mockRegister<InternInfo>("InternInfo", [
  {
    id: "1",
    userId: "7",
    program: "BS Computer Science",
    schoolYear: "2024-2025",
    trainingCompany: "Accenture",
    remainingHours: 180,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "2",
    userId: "8",
    program: "BSBA Major in Marketing",
    schoolYear: "2024-2025",
    trainingCompany: "Smart Telecom",
    remainingHours: 100,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "3",
    userId: "9",
    program: "BS Mechanical Engineering",
    schoolYear: "2024-2025",
    trainingCompany: "Petron",
    remainingHours: 0,
    requiredHours: 300,
    accomplished: true,
  },
  {
    id: "4",
    userId: "10",
    program: "BS Information Technology",
    schoolYear: "2024-2025",
    trainingCompany: "Globe Telecom",
    remainingHours: 250,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "5",
    userId: "11",
    program: "BSBA Major in Finance",
    schoolYear: "2024-2025",
    trainingCompany: "BPI Bank",
    remainingHours: 150,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "6",
    userId: "12",
    program: "BS Hospitality Management",
    schoolYear: "2024-2025",
    trainingCompany: "Shangri-La Hotels",
    remainingHours: 280,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "7",
    userId: "13",
    program: "BS Information Technology",
    schoolYear: "2024-2025",
    trainingCompany: "Shangri-La Hotels",
    remainingHours: 50,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "8",
    userId: "14",
    program: "BS Computer Engineering",
    schoolYear: "2024-2025",
    trainingCompany: "IBM Philippines",
    remainingHours: 200,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "9",
    userId: "15",
    program: "BS Architecture",
    schoolYear: "2024-2025",
    trainingCompany: "Ayala Land",
    remainingHours: 90,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "10",
    userId: "16",
    program: "BS Civil Engineering",
    schoolYear: "2024-2025",
    trainingCompany: "DMCI Homes",
    remainingHours: 30,
    requiredHours: 300,
    accomplished: true,
  },
  {
    id: "11",
    userId: "17",
    program: "BS Information Systems",
    schoolYear: "2024-2025",
    trainingCompany: "Accenture",
    remainingHours: 270,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "12",
    userId: "18",
    program: "BS Computer Science",
    schoolYear: "2024-2025",
    trainingCompany: "Microsoft PH",
    remainingHours: 200,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "13",
    userId: "19",
    program: "BS Psychology",
    schoolYear: "2024-2025",
    trainingCompany: "Makati Medical Center",
    remainingHours: 120,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "14",
    userId: "20",
    program: "BS Entrepreneurship",
    schoolYear: "2024-2025",
    trainingCompany: "Shopee PH",
    remainingHours: 300,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "15",
    userId: "21",
    program: "BS Accountancy",
    schoolYear: "2024-2025",
    trainingCompany: "PwC Philippines",
    remainingHours: 0,
    requiredHours: 300,
    accomplished: true,
  },
  {
    id: "16",
    userId: "22",
    program: "BS Marketing Management",
    schoolYear: "2024-2025",
    trainingCompany: "Unilever PH",
    remainingHours: 260,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "17",
    userId: "23",
    program: "BS Criminology",
    schoolYear: "2024-2025",
    trainingCompany: "PNP Headquarters",
    remainingHours: 280,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "18",
    userId: "24",
    program: "BS Nursing",
    schoolYear: "2024-2025",
    trainingCompany: "St. Luke’s Medical Center",
    remainingHours: 100,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "19",
    userId: "25",
    program: "BS Tourism",
    schoolYear: "2024-2025",
    trainingCompany: "Cebu Pacific",
    remainingHours: 250,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "20",
    userId: "26",
    program: "BS Electronics Engineering",
    schoolYear: "2024-2025",
    trainingCompany: "Intel PH",
    remainingHours: 220,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "21",
    userId: "27",
    program: "BS Accountancy",
    schoolYear: "2024-2025",
    trainingCompany: "SGV & Co.",
    remainingHours: 0,
    requiredHours: 300,
    accomplished: true,
  },
  {
    id: "22",
    userId: "28",
    program: "BS IT",
    schoolYear: "2024-2025",
    trainingCompany: "Globe Telecom",
    remainingHours: 50,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "23",
    userId: "29",
    program: "BS Information Systems",
    schoolYear: "2024-2025",
    trainingCompany: "Accenture",
    remainingHours: 90,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "24",
    userId: "30",
    program: "BS Computer Science",
    schoolYear: "2024-2025",
    trainingCompany: "Oracle Philippines",
    remainingHours: 150,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "25",
    userId: "31",
    program: "BS Chemical Engineering",
    schoolYear: "2024-2025",
    trainingCompany: "Nestlé PH",
    remainingHours: 240,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "26",
    userId: "32",
    program: "BS Architecture",
    schoolYear: "2024-2025",
    trainingCompany: "Megaworld",
    remainingHours: 60,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "27",
    userId: "33",
    program: "BS HRM",
    schoolYear: "2024-2025",
    trainingCompany: "Marriott Hotel",
    remainingHours: 300,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "28",
    userId: "34",
    program: "BS Mechanical Engineering",
    schoolYear: "2024-2025",
    trainingCompany: "San Miguel Corp.",
    remainingHours: 280,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "29",
    userId: "35",
    program: "BS Computer Science",
    schoolYear: "2024-2025",
    trainingCompany: "Google PH",
    remainingHours: 200,
    requiredHours: 300,
    accomplished: false,
  },
  {
    id: "30",
    userId: "36",
    program: "BS Information Technology",
    schoolYear: "2024-2025",
    trainingCompany: "Amazon Web Services",
    remainingHours: 150,
    requiredHours: 300,
    accomplished: false,
  },

  ...Array.from({ length: 50 }, (_, i) => {
    const id = 31 + i;
    const companies = [
      "IBM Philippines",
      "Ayala Land",
      "Accenture",
      "Globe Telecom",
      "Smart Telecom",
      "Petron",
      "DMCI Homes",
      "Unilever PH",
      "Cebu Pacific",
      "Nestlé PH",
      "PwC Philippines",
      "SGV & Co.",
      "San Miguel Corp.",
      "Microsoft PH",
      "Google PH",
    ];
    const programs = [
      "BS Computer Science",
      "BS Information Technology",
      "BS Information Systems",
      "BS Accountancy",
      "BSBA Major in Marketing",
      "BSBA Major in Finance",
      "BS Hospitality Management",
      "BS Mechanical Engineering",
      "BS Architecture",
      "BS Tourism",
    ];
    const trainingCompany = companies[i % companies.length];
    const program = programs[i % programs.length];

    return {
      id: String(id),
      userId: String(40 + i),
      program,
      schoolYear: "2024-2025",
      trainingCompany,
      remainingHours: Math.floor(Math.random() * 301),
      requiredHours: 300,
      accomplished: Math.random() > 0.7,
    };
  }),
]);
